# Generated by Django 3.1.2 on 2020-11-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_customer_conform_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='conform_password',
            new_name='conferm_password',
        ),
    ]
