# Generated by Django 3.1.2 on 2020-11-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20201122_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='conferm_password',
            new_name='confirm_password',
        ),
    ]
